version: '3'

services: 

    opentsdb: # opentsdb 서비스 이미지
      image: petergrace/opentsdb-docker:latest
      restart: always
      ports:
          - "60010:4242"
      volumes:
        - "./opentsdb_volume:/data/hbase"
      container_name: opentsdb_container


    app_csv_to_opentsdb: # csv파일들의 데이터를 opentsdb에 저장해주는 파이썬 코드의 이미지
      image: goo99999/file_to_tsdb:v3
      #container에 ssh 접속을 위해 로컬포트:컨테이너내부포트 포트포워딩
      #ports:
      # - "5004:22"
      volumes:
        - "./app_file2otsdb_volume:/app/FILE2TSDB"
        - "./files:/app/files"
      environment:
        - TSDB_IP=keti-ev.iptime.org  # 저장할 opentsdb의 ip
        - TSDB_PORT=60010 # 저장할 opentsdb의 port
        - FIELDNAME=DRIVE_SPEED|DRIVE_LENGTH_TOTAL # openTSDB에 저장할 CSV파일 데이터의 컬럼명 ('|'문자로 여러 컬럼 저장가능)
        - IDFIELD=PHONE_NUM # openTSDB에 저장할 CSV파일의 데이터 중 carid 컬럼명
        - TIMEFIELD=RECORD_TIME # openTSDB에 저장할 CSV파일의 시간 데이터 컬럼명
        - METRIC=test_data_set # openTSDB에 저장할 metric(table) 명
        - PN=2 # csv데이터를 json format으로 변환시키는 프로세스의 수 (PC 사양에 따라 알맞게 지정) 
        - CN=2 # 변환된 json데이터를 opentsdb에 전송해주는 프로세스의 수 (PC 사양에 따라 알맞게 지정) 
      container_name: csv2otsdb_container
      # --link 옵션을 이용해 opentsdb container 와 link를 맺을 것을 설정한다. 
      # 이렇게 설정하면, csv_to_opentsdb container 는 opentsdb container 를 IP 가 아닌 container의 이름을 이용해 통신할 수 있다.
      # csv_to_opentsdb container의 /etc/hosts 파일에 opentsdb container의 IP 주소와 host명이 등록되어 있다.
      links:
        - opentsdb:db
        

    app_opentsdb_read: # opentsdb의 data를 쿼리하여 총 data points의 수를 count해주는 파이썬 코드의 이미지
      image: goo99999/otsdb_read:v3
      #container에 ssh 접속을 위해 로컬포트:컨테이너내부포트 포트포워딩
      #ports:
      # - "5004:22"
      volumes:
        - "./app_otsdb_read_volume:/app/READ_TSDB"
      environment:
        - TSDB_IP=keti-ev.iptime.org  # 저장할 opentsdb의 ip
        - TSDB_PORT=60010 # 쿼리할 opentsdb port
        - TSDB_METRIC=test_data_set # 쿼리할 opentsdb metric명
        - QUERY_TIME_START=2020/01/01-00:00:00 # 쿼리할 opentsdb 시작 시간
        - QUERY_TIME_END=2020/01/08-00:00:00 # 쿼리할 opentsdb 끝 시간
        - CAR_ID=none # 쿼리할 차량 번호 ('none' 입력시 전체 차량 쿼리, '|' 문자로 여러 차량 쿼리 가능)
        - QUERY_TIME_UNIT=d # 쿼리할 전체기간 중 나눠 쿼리할 단위 ('d' = days, 'h' = hours, 'm' = minutes)
        - QUERY_TIME_LONG=1 # 쿼리할 전체기간 중 나눠 쿼리할 단위의 크기 (timeunit='d', timelong='7' => 7days)
      container_name: otsdb_read_container
      # --link 옵션을 이용해 opentsdb container 와 link를 맺을 것을 설정한다. 
      # 이렇게 설정하면, opentsdb_read container 는 opentsdb container 를 IP 가 아닌 container의 이름을 이용해 통신할 수 있다.
      # opentsdb_read container의 /etc/hosts 파일에 opentsdb container의 IP 주소와 host명이 등록되어 있다.
      links:
        - opentsdb:db
