version: '2'  
services:  
  influxdb:  
    image: "influxdb:1.7"
    container_name: influxdb_container
    restart: always
    ports:  
      - "8086:8086"  
    volumes:
      - ./influxdb:/var/lib/influxdb  