version: '3'

services: 
    mariadb:
        image: mariadb    # mariaDB 서비스
        ports: 
            - 3307:3306   # service port를 정의 (local:container)
        restart: always   # container를 실행할 때 항상 이미 수행중이라면 재시작
        volumes:          # 예기치 못한 문제로 컨테이너가 종료되어도 DB의 데이터와 설정을 보전 및 백업하기 위한 볼륨 공유 (local : container) 
            - ./mariadb_volumes/data:/var/lib/mysql
            - ./mariadb_volumes/conf.d:/etc/mysql/conf.d
        environment:      # mariaDB 구축시 환경 변수
            MYSQL_USER: keti
            MYSQL_PASSWORD: keti1234
            MYSQL_ROOT_PASSWORD: keti1234
            MYSQL_DATABASE : testdb
        container_name: mariadb_container


    app_csv_to_maria:
      image: goo99999/csv2maria:v2
      #container에 ssh 접속을 위해 로컬포트:컨테이너내부포트 포트포워딩
      #ports:
      # - "5004:22"
      volumes:
          - "./app_csv2maria_volumes:/app/CSV2MARIA"
          - "./CSV_in:/app/CSV_in"
      environment:
          - MARIA_IP=keti-ev.iptime.org # 접속할 MARIA디비의 ip
          - MARIA_PORT=3307 # 접속할 MARIA디비의 port
          - MARIA_USER=root # 접속할 MARIA디비의 루트 사용자명
          - MARIA_PASSWORD=keti1234 # 접속할 MARIA디비의 루트 사용자 비밀번호
          - MARIA_DB_NAME=cardata # 접속하거나 새로 생성할 MARIA디비의 DB이름
          - MARIA_TABLE_NAME=table1 # 접속하거나 새로 생성할 MARIA디비의 TABLE이름
      container_name: csv2maria_container
      depends_on: # 지정한 컨테이너가 구동 완료되면 본 컨테이너 시동
          - mariadb
    
    app_read_maria:
      image: goo99999/read_maria:v1
      #container에 ssh 접속을 위해 로컬포트:컨테이너내부포트 포트포워딩
      #ports:
      # - "5004:22"
      volumes:
          - "./app_read_maria_volumes:/app/READ_MARIA"
      environment:
          - MARIA_IP=keti-ev.iptime.org # 접속할 MARIA디비의 ip
          - MARIA_PORT=3307 # 접속할 MARIA디비의 port
          - MARIA_USER=root # 접속할 MARIA디비의 루트 사용자명
          - MARIA_PASSWORD=keti1234 # 접속할 MARIA디비의 루트 사용자 비밀번호
          - MARIA_DB_NAME=cardata # 접속할 MARIA디비의 DB이름
          - MARIA_TABLE_NAME=table1 # 접속할 MARIA디비의 TABLE이름
          - QUERY_ROWS=10 # table로부터 쿼리할 총 row 수 
      container_name: read_maria_container
      depends_on: # 지정한 컨테이너가 구동 완료되면 본 컨테이너 시동
          - app_csv_to_maria